my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list[1]=dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 23578164713
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 26262444164
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 27051422601
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 24317847610
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 22474368790
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 22536795815
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 19289811770
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 17688829038
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 25755847676
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 22713306074
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 20886927675
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 26465710031
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 20037093156
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 25360510873
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 24521693760
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 20998667371
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 19677991201
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 23827234991
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v2 running time = 22789650864
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
h_list: dfs.blockreport.incremental.intervalMsec@@@hdfs:DataNode@@@-1@@@0@@@10000000
vv_mode: v1v2
result: FAIL
failureMessage: expected:<3> but was:<1>
stackTrace: java.lang.AssertionError: expected:<3> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.doTest(TestSaslDataTransfer.java:210)
	at org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer.testPrivacy(TestSaslDataTransfer.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v1v1 running time = 26711607638
updating test result for file org.apache.hadoop.hdfs.protocol.datatransfer.sasl.TestSaslDataTransfer#testPrivacy
v2v2 running time = 24981857010
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 487
0
