my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list[1]=dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 34121184911
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363867136> but was:<898363899904>
stackTrace: java.lang.AssertionError: expected:<898363867136> but was:<898363899904>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 34709335565
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 31277657624
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 32105760029
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363867136> but was:<898363899904>
stackTrace: java.lang.AssertionError: expected:<898363867136> but was:<898363899904>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 36688605089
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 31889798175
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 34717134221
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363867136> but was:<898363899904>
stackTrace: java.lang.AssertionError: expected:<898363867136> but was:<898363899904>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 37601015612
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 37861324644
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 33780185668
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363867136> but was:<898363899904>
stackTrace: java.lang.AssertionError: expected:<898363867136> but was:<898363899904>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 40379920886
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 42524682648
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 38429149347
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363867136> but was:<898363899904>
stackTrace: java.lang.AssertionError: expected:<898363867136> but was:<898363899904>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 36031107957
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 39271001479
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 34838832174
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363899904> but was:<898363867136>
stackTrace: java.lang.AssertionError: expected:<898363899904> but was:<898363867136>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 38049255876
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 37330485747
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v2 running time = 37141493775
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
h_list: dfs.datanode.du.reserved@@@hdfs:DataNode@@@-2@@@0@@@16384
vv_mode: v1v2
result: FAIL
failureMessage: expected:<898363867136> but was:<898363899904>
stackTrace: java.lang.AssertionError: expected:<898363867136> but was:<898363899904>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.checkFailuresAtDataNode(TestDataNodeVolumeFailureReporting.java:671)
	at org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting.testMultipleVolFailuresOnNode(TestDataNodeVolumeFailureReporting.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v1v1 running time = 41367744753
updating test result for file org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureReporting#testMultipleVolFailuresOnNode
v2v2 running time = 45416916098
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 775
0
